### PR TITLE
msm8998: Enable Aambient Display

### PR DESCRIPTION
**Pull request by 0xnth**
-msm8998: import oneplus 3 doze package
-msm8998: rename doze package menu
-msm8998: enable AOD overlay and Doze Mode

Signed-off-by: mrhainavn <mrhainavn@gmail.com>

### CODE REVIEW

**Comment by 0xnth** [comment]
@Meninblack007 @gtpitch Please merge them to fix doze mode not work for op5t. Thanks!

**Comment by gtpitch** [comment]
No. I'm going to add aosp's pickup gesture but we aren't adding OnePlus doze

**Comment by 0xnth** [comment]
@gtpitch
ok. Thanks, so can you disable/remove "always on display" for this device?

**Comment by gtpitch** [comment]
Kinda doubt it. It was basically the most requested feature before it was enabled. You can obviously just turn it off

**Comment by 0xnth** [comment]
@gtpitch
as you just said above about "AOSP Pickup Gesture" but it not show in settings, and after although i already apply Substratum "enable Always On" then it show in settings but it still not work with Pickup gesture.
there is a conflict in rom source? or you need remove some commit for always on to Ambient display work again

**Pull request closed without merging**
